global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: adresse
      - source_labels: [__param_target]
        target_label: aaaaa
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: blackbox-demo
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # This is your blackbox exporter.
    static_configs:
      - targets: ['google.com']

  - job_name: local-node-exporter
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]

  - job_name: push-gateway
    honor_labels: true
    static_configs:
      - targets: [ push-gateway:9091 ]

  - job_name: spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
